// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqt2rSK3oUJ54SuNEQzhJDRJv71AUVqUc',
    appId: '1:146641783262:web:5e7d876ffb14aea6b4354f',
    messagingSenderId: '146641783262',
    projectId: 'flower-flutter-7625a',
    authDomain: 'flower-flutter-7625a.firebaseapp.com',
    storageBucket: 'flower-flutter-7625a.appspot.com',
    measurementId: 'G-NRZ8J4RPXT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmb4Y2bnKQkcneYrFYb8IJDfGeiovs63M',
    appId: '1:146641783262:android:bdf130d300846eddb4354f',
    messagingSenderId: '146641783262',
    projectId: 'flower-flutter-7625a',
    storageBucket: 'flower-flutter-7625a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyWK5j6FwD00i_At7HAl5Wz2NrT0jOivE',
    appId: '1:146641783262:ios:bae6d21a6d089810b4354f',
    messagingSenderId: '146641783262',
    projectId: 'flower-flutter-7625a',
    storageBucket: 'flower-flutter-7625a.appspot.com',
    iosClientId: '146641783262-h87fdq9ba5ab36tf0culvt7lpo1iucov.apps.googleusercontent.com',
    iosBundleId: 'com.example.flowerFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyWK5j6FwD00i_At7HAl5Wz2NrT0jOivE',
    appId: '1:146641783262:ios:bae6d21a6d089810b4354f',
    messagingSenderId: '146641783262',
    projectId: 'flower-flutter-7625a',
    storageBucket: 'flower-flutter-7625a.appspot.com',
    iosClientId: '146641783262-h87fdq9ba5ab36tf0culvt7lpo1iucov.apps.googleusercontent.com',
    iosBundleId: 'com.example.flowerFlutter',
  );
}
